//*****************************************************************************
// Interim / Beggining of Spring Semester Exosite Testing Project
// Based on:
// https://github.com/exosite-garage/arduino_exosite_library/blob/master/examples/ExoEthernetGettingStarted/ExoEthernetGettingStarted.ino
// http://www.instructables.com/id/Arduino-Ethernet-Shield-Tutorial/step3/Get-started/
// https://www.arduino.cc/en/Main/ArduinoEthernetShield
// Author: Anthony Jin
// Version 1.0, Jan. 30, 2016
//*****************************************************************************

#include <SPI.h>
#include <EEPROM.h>
#include <Ethernet.h>
#include <Exosite.h>

/*==============================================================================
* Configuration Variables
* Change these variables to your own settings.
*=============================================================================*/
byte macData[] = { 0x00, 0xAA, 0xBB, 0xCC, 0xDE, 0x02 };        // Random MAC address

// Unique identifier generated by Exosite
char unique_id[11] = "00224C49FC"; 

/*============================================================================== 
 * Variable Declarations
 *============================================================================*/
// Based on data source
const String readString = "d2"; // digital 2

// Number of Errors before we try a reprovision.
const unsigned char reprovisionAfter = 3;
/*==============================================================================
* End of Configuration Variables
*=============================================================================*/

unsigned char errorCount = reprovisionAfter;  // Force Provision On First Loop
char macString[18];  // Used to store a formatted version of the MAC Address

EthernetClient client;
Exosite exosite(&client);

String tempString;
int index = 0;
int lastIndex = -1;


/*==============================================================================
* Setup
* Arduino setup function.
*=============================================================================*/
void setup() {
  Serial.begin(115200); // 115200 baud rate
  Serial.println(F("Boot"));

  pinMode(2, OUTPUT); //assume using D2 as output to control remotely
  
  // Create MAC Address String in the format FF:FF:FF:FF:FF:FF
  snprintf(macString, 18, "%02X:%02X:%02X:%02X:%02X:%02X",
           macData[0], macData[1], macData[2], macData[3], macData[4], macData[5]);

  Serial.println(F("setting up Ethernet Connection..."));
  
  // Setup Ethernet Connection
  if (Ethernet.begin(macData) == 0) {
    Serial.println("Failed to configure Ethernet using DHCP");
    // no point in carrying on, so do nothing forevermore:
    for (;;)
      ;
  }
  
  // Print Some Useful Info
  Serial.print(F("MAC Address: "));
  Serial.println(macString);

  Serial.print(F("IP Address: "));
  Serial.println(Ethernet.localIP());

  Serial.print(F("Unique Identifier: "));
  Serial.println(unique_id);
  
  Serial.print(F("Exo Arduino Lib Ver: "));
  Serial.println(ACTIVATOR_VERSION);
}

/*==============================================================================
* loop
* Arduino loop function.
*=============================================================================*/
void loop() {
  String writeString = "";
  String returnString = "";
  index = 0;
  lastIndex = -1;
  
  // Check if we should reprovision.
  if (errorCount >= reprovisionAfter) {
    if (exosite.provision("exosite", "ard-generic", unique_id)) {
      errorCount = 0;
    }
  }
  String uptime_str = String(millis()/1000);
  writeString += "uptime="+ uptime_str;

  //GET ANALOG 0 VALUE
  //get average of a number of readings
  int avgValue=0;
  int readings = 0;
  unsigned long avgTot = 0;
  int avgCnt = 0;

  while(readings<10)
  {
    avgTot += analogRead(A0);
    avgCnt += 1;
    avgValue = avgTot/avgCnt;
    readings++;
  }
  String analog0_str = String(avgValue);
  writeString += "&a0="+ analog0_str;
  
  //Make Write and Read request to Exosite Platform
//  Serial.println("---- Do Read and Write ----");
  if (exosite.writeRead(writeString, readString, returnString)) {
//    Serial.println("OK");
//    Serial.print("Returned: ");
//    Serial.println(returnString);
//    Serial.println("Parse out dataport alias values");
    errorCount = 0;
    for(;;){
      index = returnString.indexOf("=", lastIndex+1);
      if(index != 0){
        String alias = "";
        tempString = returnString.substring(lastIndex+1, index);
//        Serial.print(F("Alias: "));
//        Serial.println(tempString);
        lastIndex = returnString.indexOf("&", index+1);
        alias = tempString;
        if(lastIndex != -1){
          tempString = returnString.substring(index+1, lastIndex);
        }else{
          tempString = returnString.substring(index+1);
        }
        if (alias == "d2"){
          if(tempString == "1"){
            digitalWrite(2, 1);
//            Serial.println("set Digital2 to 1");
          }else if(tempString == "0"){
            digitalWrite(2, 0);
//            Serial.println("set Digital2 to 0");
          }else{
//            Serial.print(F("Unknown Setting: "));
//            Serial.println(tempString);
          }
        } else if (alias == "msg"){
//          Serial.print("Message: ");
//          Serial.println(tempString);
        } else {
//          Serial.println("Unknown Alias Dataport");
        }
        if(lastIndex == -1)
          break;        
      }else{
//        Serial.println(F("No Index"));
        break;
      }
    } 
  } else {
//    Serial.println("No Connection");
    errorCount++;
  }
  delay(5000); // 1000 = 1 sec
}
